// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthMiddleware(arg1) {
  return window['go']['main']['App']['AuthMiddleware'](arg1);
}
