// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {echo} from '../models';

export function AuthMiddleware(arg1:echo.HandlerFunc):Promise<echo.HandlerFunc>;
